### ISSUE TITLE
[Bug]: 请问报错这个怎么解决？

### ISSUE THREAD

**Issue by qq263424205** [XiaoXinYo/Chat-WebAPI#6]
### 在提交前请确保以下这些

- [X] ChatGPT,EdgeGPT,BingImageCreator,GoogleBard,easy-ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

Windows

### Python版本

python3.10.11

### 问题

ImportError: cannot import name 'ConversationStyle' from 'EdgeGPT' (D:\python\lib\site-packages\EdgeGPT\__init__.py)

### 触发

python main.py

### 报错

D:\demo\Chat-API-main>python main.py
Traceback (most recent call last):
  File "D:\demo\Chat-API-main\main.py", line 6, in <module>
    from view import chatgpt, bing, bard, ernie
  File "D:\demo\Chat-API-main\view\bing.py", line 8, in <module>
    from EdgeGPT import ConversationStyle
ImportError: cannot import name 'ConversationStyle' from 'EdgeGPT' (D:\python\lib\site-packages\EdgeGPT\__init__.py)

请问要怎么解决？

**Comment by kkkkiven** [comment]
同样的问题，求解

**Comment by kkkkiven** [comment]
找到了。我把导入的时候from EdgeGPT import ConversationStyle 改成from EdgeGPT.EdgeGPT import ConversationStyle。这样就能用了

**Comment by ykaiqx** [comment]
正在修复。。。

**Comment by ykaiqx** [comment]
已更新
