### ISSUE TITLE
[Bug]: bing 报错 KeyError: 'conversationSignature'

### ISSUE THREAD

**Issue by abinjob** [XiaoXinYo/Chat-WebAPI#9]
### 在提交前请确保以下这些

- [X] Chat-WebAPI为最新版本
- [X] GoogleBard,EdgeGPT,BingImageCreator,revChatGPT,easy-ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

Windows

### Python版本

3.10

### 问题

Traceback (most recent call last):
  File "F:\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\fastapi\applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\Chat-WebAPI-main\main.py", line 56, in middleware
    response = await call_next(request)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "F:\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Chat-WebAPI-main\view\bing.py", line 101, in ask
    token, chatBot = chat_bot.generateChatBot('Bing')
  File "D:\Chat-WebAPI-main\module\chat_bot.py", line 28, in generateChatBot
    chatBot = EdgeGPT.EdgeGPT.Chatbot(proxy=config.PROXY, cookies=BING_COOKIE)
  File "F:\Python\Python310\lib\site-packages\EdgeGPT\EdgeGPT.py", line 28, in __init__
    self.chat_hub: ChatHub = ChatHub(
  File "F:\Python\Python310\lib\site-packages\EdgeGPT\chathub.py", line 42, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'

### 触发

post
http://127.0.0.1:222/bing/ask
{"question":"用我爱刘亦菲写首藏头诗"}

### 报错

Traceback (most recent call last):
  File "F:\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\fastapi\applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\Chat-WebAPI-main\main.py", line 56, in middleware
    response = await call_next(request)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "F:\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Chat-WebAPI-main\view\bing.py", line 101, in ask
    token, chatBot = chat_bot.generateChatBot('Bing')
  File "D:\Chat-WebAPI-main\module\chat_bot.py", line 28, in generateChatBot
    chatBot = EdgeGPT.EdgeGPT.Chatbot(proxy=config.PROXY, cookies=BING_COOKIE)
  File "F:\Python\Python310\lib\site-packages\EdgeGPT\EdgeGPT.py", line 28, in __init__
    self.chat_hub: ChatHub = ChatHub(
  File "F:\Python\Python310\lib\site-packages\EdgeGPT\chathub.py", line 42, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'

### 其他

无

**Comment by abinjob** [comment]
{
    "code": 500,
    "message": "未知错误",
    "data": null
}

**Comment by ykaiqx** [comment]
EdgeGPT 项目已停止维护 [9dd4f3fb959091fd38423105f7bcba78d54da821](https://github.com/acheong08/EdgeGPT/commit/9dd4f3fb959091fd38423105f7bcba78d54da821)

**Comment by abinjob** [comment]
这么说就是用不了来？

**Comment by ykaiqx** [comment]
目前来看确实是这么个情况
